# Generated by Django 3.2.18 on 2023-03-15 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0002_alter_fileupload_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='user',
            new_name='name',
        ),
    ]
