# Generated by Django 3.2.18 on 2023-03-24 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0006_uploadmatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadmatch',
            name='name_text',
        ),
    ]
